openapi: 3.0.0
info:
  version: '1.0'
  title: 'Daytona API'
  description: 'This is Daytona API'
paths: {}
components:
  schemas:
    user:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - countryId
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        bio:
          type: string
        countryId:
          type: integer
        stateId:
          type: integer
        zip:
          type: string
        statusId:
          type: integer
        languageId:
          type: integer
        dateFormatId:
          type: integer
        timeZoneId:
          type: integer
        imagePath:
          type: string
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/AliakseiDudko/DaytonaAPI/1.0