openapi: 3.0.0
info:
  version: '1.0'
  title: 'Daytona API'
  description: 'This is Daytona API'
paths: {}

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/AliakseiDudko/DaytonaAPI/1.0